---
- name: Install ZSH
  hosts: localhost
  connection: local

  tasks:
    - name: Include ZSH tasks
      import_tasks: tasks/zsh.yml

    - name: Include ZSH tasks
      import_tasks: tasks/amazon_zsh.yml
      tags: ["never", "amz"]
