---
- hosts: localhost
  vars:
    USER: 'vyktor.sokurenko'

  pre_tasks:
    - name: install python for Ansible
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)
      changed_when: False
      tags: python

  tasks:
  - name: populate service facts
    no_log: true
    service_facts:

  - name: show user and hostname
    debug:
      msg: "Setup configuration for user {{ USER }} in {{ inventory_hostname }}"
    failed_when: USER is not defined

  - name: check if any version of agent is already installed
    stat:
      path: /usr/sbin/lightdm
    register: lightdm_installed

  - name: include screen tasks
    include_tasks: screen.yml

  - name: include tilda tasks
    include_tasks: tilda.yml

  - name: include vim tasks
    include_tasks: vim.yml

  - name: include bash_it tasks
    include_tasks: bash_it.yml

  - name: include sublime_text tasks
    include_tasks: sublime.yml

  become: yes
