- name: install packages for zsh
  package:
    name: ["zsh", "git", "python3-pygments"]
    state: latest
  become: true

- name: clone Oh-My-ZSH if not present
  command: "git clone -c core.autocrlf=input --depth=1 https://github.com/ohmyzsh/ohmyzsh .oh-my-zsh"
  args:
    chdir: "{{ item }}"
    creates: "{{ item }}/.oh-my-zsh"
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  loop:
    - /root
    - /etc/skel
  register: ohmyzshinstall
  become: true

- name: clone powerlevel10k repo
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ item }}/.oh-my-zsh/custom/themes/powerlevel10k"
  when: ohmyzshinstall is success
  loop:
    - /etc/skel
    - /root
  register: powerlevel10krepo
  become: true

- name: clone powerlevel10k repo
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: "/tmp/fonts"
  when: ohmyzshinstall is success
  register: clone_fonts
  become: true

- name: install Powerline fonts
  command: "bash install.sh"
  args:
    chdir: /tmp/fonts
  when: clone_fonts is success
  ignore_errors: true
  become: true

- name: ensure completions and functions dir
  file:
    path: "{{ item.0 }}/.oh-my-zsh/{{ item.1 }}"
    state: directory
    mode: "0755"
  loop: "{{ root_folders|product(zsh_folders)|list }}"
  vars:
    root_folders:
      - /root
      - /etc/skel
    zsh_folders:
      - "completions"
      - "functions"
  register: zsh_dirs
  when: ohmyzshinstall is success
  become: true

- name: clone zsh-autosuggestions repo
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ item }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: true
  when: ohmyzshinstall is success
  loop:
    - /root
    - /etc/skel
  register: zsh_autosuggestions

- name: ensure powerlevel10k theme settings file
  copy:
    src: p10k.zsh
    dest: "{{ item }}/.p10k.zsh"
  loop:
    - /root
    - /etc/skel
  when: powerlevel10krepo is success
  become: true

- name: Set the aliases list
  set_fact:
    ZSH_aliases:
      - alias nullrepo='git add . && git stash && git stash drop'
      - alias ap='ansible-playbook'
      - alias logvault="vault login -method=userpass username=${USER}"
      - alias ccat='pygmentize -g '
      - alias showcert='openssl x509 -text -noout -in '
      - alias xx='sudo -s --shell /bin/zsh'
      - alias ..="cd .."
      - alias ...="cd ../../"
      - alias gtc='git add . && git commit -m "`curl -s http://whatthecommit.com/index.txt`" && git push'
      - alias gsv='git status -vv'
      - alias cgd='if git rev-parse --is-inside-work-tree --quiet >/dev/null 2>/dev/null; then cd $(git rev-parse --show-toplevel); else echo "Not in Git repository!"; fi'

- name: Set the folder shortcut list
  set_fact:
    ZSH_folder_shortcuts:
      - hash -d volumes=/var/lib/docker/volumes

- name: define .zshrc from template
  template:
    dest: "{{ item }}/.zshrc"
    src: zshrc.j2
    mode: '0664'
  loop:
    - /root
    - /etc/skel
  when: ohmyzshinstall is success
  register: copyzshrc
  become: true
