- name: install vim packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - vim
    - git
  become: true

- name: List of Vim plugins
  set_fact:
    VIM_plugins:
      - 'preservim/nerdtree'
      - 'pearofducks/ansible-vim'
      - 'Xuyuanp/nerdtree-git-plugin'
      - 'majutsushi/tagbar'
      - 'arcticicestudio/nord-vim'
      - 'itchyny/lightline.vim'
      - 'Yggdroot/indentLine'
      - 'tpope/vim-fugitive'
      - 'ekalinin/Dockerfile.vim'
      - 'chr4/nginx.vim'
      - 'itchyny/lightline.vim'
      - 'tpope/vim-abolish'

- name: create autoload directory for Vim
  file:
    state: directory
    path: "{{ lookup('env','HOME') }}/.vim/autoload"
  register: autoload_vim

- name: get plug.vim
  get_url:
    url: "https://raw.github.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ lookup('env','HOME') }}/.vim/autoload/plug.vim"
    mode: 0644
  register: get_plug_vim
  when: autoload_vim is success

- name: define .vimrc
  template:
    dest: "{{ lookup('env','HOME') }}/.vimrc"
    src: vimrc.j2
    mode: '0664'
  when: get_plug_vim is success
