- name: ensure config dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  loop:
  - '/home/{{ ansible_user }}/.themes'
  - '/home/{{ ansible_user }}/.icons'
  register: theme_dirs

- name: download win10 theme
  git:
    repo: 'https://github.com/B00merang-Project/Windows-10.git'
    dest: "/home/{{ ansible_user }}/.themes/Windows-10"

- name: download win10 icons
  git:
    repo: 'https://github.com/B00merang-Artwork/Windows-10.git'
    dest: "/home/{{ ansible_user }}/.icons/Windows-10"
